# Generated by Django 3.1.7 on 2021-04-19 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('daily_funding', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cookie',
        ),
    ]
