# Generated by Django 3.1.7 on 2021-04-02 02:37

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Deposit_Withdrawal',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('transaction_amount', models.DecimalField(decimal_places=0, max_digits=13)),
                ('remaining_amount', models.DecimalField(decimal_places=0, max_digits=13)),
                ('trading_time', models.DateTimeField(default=datetime.timezone)),
                ('company_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.company')),
                ('uid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
