# Generated by Django 3.1.7 on 2021-04-06 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_auto_20210402_1156'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='account_number',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='account',
            name='account_holder',
            field=models.CharField(default='', max_length=45),
        ),
        migrations.AlterField(
            model_name='account',
            name='bank',
            field=models.CharField(default='', max_length=30),
        ),
    ]
