# Generated by Django 3.1.7 on 2021-04-06 06:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0003_auto_20210402_1326'),
        ('account', '0007_auto_20210406_1453'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='deposit_withdrawal',
            unique_together={('company_id', 'trading_time', 'remaining_amount')},
        ),
    ]
