# Generated by Django 3.1.7 on 2021-04-19 11:57

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('company', '0004_company_nickname'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('username', models.CharField(default='', max_length=50)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('first_name', models.CharField(blank=True, max_length=255)),
                ('last_name', models.CharField(blank=True, max_length=255)),
                ('withdrawal_status', models.BooleanField(default=False)),
                ('withdrawal_date', models.DateTimeField(blank=True, null=True)),
                ('ucode', models.CharField(blank=True, max_length=16, null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'db_table': 'user',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Investing_Status',
            fields=[
                ('status_code', models.CharField(max_length=45, primary_key=True, serialize=False)),
                ('status_meaning', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'investing_status',
            },
        ),
        migrations.CreateModel(
            name='Investing_Type',
            fields=[
                ('type_code', models.CharField(max_length=45, primary_key=True, serialize=False)),
                ('type_meaning', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'investing_type',
            },
        ),
        migrations.CreateModel(
            name='Summary_Investing',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('investing_product', models.CharField(max_length=45)),
                ('investing_price', models.PositiveIntegerField()),
                ('company_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.company')),
                ('investing_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.investing_type')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.investing_status')),
                ('uid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'summary_investing',
                'unique_together': {('company_id', 'investing_product', 'investing_price')},
            },
        ),
        migrations.CreateModel(
            name='Register',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=500)),
                ('user_password', models.CharField(max_length=500)),
                ('company_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.company')),
                ('uid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'register',
                'unique_together': {('company_id', 'uid')},
            },
        ),
        migrations.CreateModel(
            name='Investing_Balance',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('total_investment', models.DecimalField(decimal_places=0, max_digits=13)),
                ('number_of_investing_products', models.IntegerField()),
                ('residual_investment_price', models.PositiveIntegerField()),
                ('company_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.company')),
                ('uid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'investing_balance',
                'unique_together': {('company_id', 'uid')},
            },
        ),
    ]
