# Generated by Django 3.1.7 on 2021-05-25 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20210525_1359'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='forget_pwd',
            field=models.CharField(blank=True, default=None, max_length=16, null=True),
        ),
    ]
