# Generated by Django 3.1.7 on 2021-05-25 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_customuser_forget_pwd'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='forget_pwd',
            new_name='forget_pwd_token',
        ),
    ]
