# Generated by Django 3.1.7 on 2021-04-02 02:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_p2p_company'),
    ]

    operations = [
        migrations.DeleteModel(
            name='P2P_Company',
        ),
        migrations.AlterModelOptions(
            name='customuser',
            options={},
        ),
        migrations.AlterModelTable(
            name='customuser',
            table='user',
        ),
    ]
