# Generated by Django 3.1.7 on 2021-04-02 02:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
        ('users', '0012_register'),
    ]

    operations = [
        migrations.CreateModel(
            name='Investing_Status',
            fields=[
                ('status_code', models.CharField(max_length=45, primary_key=True, serialize=False)),
                ('status_meaning', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Investing_Type',
            fields=[
                ('type_code', models.CharField(max_length=45, primary_key=True, serialize=False)),
                ('type_meaning', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Summary_Investing',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('investing_product', models.CharField(max_length=45)),
                ('investing_price', models.PositiveIntegerField()),
                ('investing_time', models.DateTimeField(default='')),
                ('company_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.company')),
                ('investing_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.investing_type')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.investing_status')),
                ('uid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Investing_Balance',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('total_investment', models.DecimalField(decimal_places=0, max_digits=13)),
                ('number_of_investing_products', models.IntegerField()),
                ('residual_investment_price', models.PositiveIntegerField()),
                ('company_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.company')),
                ('uid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
