# Generated by Django 3.1.7 on 2021-04-02 02:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_investing_balance_investing_status_investing_type_summary_investing'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='investing_balance',
            table='investing_balance',
        ),
        migrations.AlterModelTable(
            name='investing_status',
            table='investing_status',
        ),
        migrations.AlterModelTable(
            name='investing_type',
            table='investing_type',
        ),
        migrations.AlterModelTable(
            name='register',
            table='register',
        ),
        migrations.AlterModelTable(
            name='summary_investing',
            table='summary_investing',
        ),
    ]
