# Generated by Django 3.1.7 on 2021-04-05 01:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0003_auto_20210402_1326'),
        ('users', '0015_auto_20210405_1013'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='register',
            unique_together={('company_id', 'uid')},
        ),
    ]
