# Generated by Django 3.1.7 on 2021-04-06 04:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0003_auto_20210402_1326'),
        ('users', '0018_auto_20210405_1344'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='investing_balance',
            unique_together={('company_id', 'uid')},
        ),
        migrations.AlterUniqueTogether(
            name='summary_investing',
            unique_together={('company_id', 'uid')},
        ),
    ]
