# Generated by Django 3.1.7 on 2021-04-06 08:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0003_auto_20210402_1326'),
        ('users', '0019_auto_20210406_1355'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='summary_investing',
            unique_together={('company_id', 'investing_product', 'investing_price')},
        ),
    ]
