# Generated by Django 3.1.7 on 2021-04-06 08:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0020_auto_20210406_1719'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='summary_investing',
            name='investing_time',
        ),
    ]
