# Generated by Django 3.1.7 on 2021-04-14 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0021_remove_summary_investing_investing_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='ucode',
            field=models.CharField(blank=True, max_length=16, null=True, unique=True),
        ),
    ]
