# Generated by Django 3.1.7 on 2021-04-09 17:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('notice_board', '0003_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='noticeboard',
            name='category_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='notice_board.category'),
        ),
    ]
