# Generated by Django 3.1.7 on 2021-04-12 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notice_board', '0004_noticeboard_category_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('question', models.CharField(max_length=100)),
                ('answer', models.CharField(max_length=200)),
                ('view', models.IntegerField()),
                ('order', models.IntegerField()),
            ],
        ),
    ]
