# Generated by Django 3.1.7 on 2021-04-12 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notice_board', '0005_faq'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='faq',
            table='faq',
        ),
    ]
