# Generated by Django 3.1.7 on 2021-04-13 11:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('notice_board', '0007_auto_20210412_1401'),
    ]

    operations = [
        migrations.CreateModel(
            name='Point_action',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('action', models.CharField(max_length=50)),
                ('point_value', models.IntegerField()),
                ('limit_number_of_day', models.SmallIntegerField()),
            ],
            options={
                'db_table': 'point_action',
            },
        ),
        migrations.CreateModel(
            name='Point_List',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('point', models.IntegerField()),
                ('total_point', models.IntegerField()),
                ('date', models.DateTimeField()),
                ('detail_action', models.CharField(max_length=50)),
                ('action_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='notice_board.point_action')),
                ('uid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
