# Generated by Django 3.1.7 on 2021-04-13 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notice_board', '0008_point_action_point_list'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='point_list',
            table='point_list',
        ),
    ]
