# Generated by Django 3.1.7 on 2021-04-13 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notice_board', '0009_auto_20210413_1107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='point_list',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False, unique=True),
        ),
    ]
