# Generated by Django 3.1.7 on 2021-04-13 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notice_board', '0010_auto_20210413_1148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='point_action',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='point_list',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
