# Generated by Django 3.1.7 on 2021-04-13 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notice_board', '0011_auto_20210413_1150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='point_list',
            name='total_point',
            field=models.IntegerField(default=0),
        ),
    ]
