# Generated by Django 3.1.7 on 2021-05-31 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notice_board', '0012_auto_20210413_1356'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category_id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
