# Generated by Django 3.1.7 on 2021-06-04 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notice_board', '0013_auto_20210531_1620'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='flag',
            field=models.BooleanField(default=False),
        ),
    ]
