# Generated by Django 3.1.7 on 2021-06-03 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_page', '0002_auto_20210603_1041'),
    ]

    operations = [
        migrations.AddField(
            model_name='admincategory',
            name='url',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
