# Generated by Django 3.1.7 on 2021-04-02 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('company_name', models.CharField(max_length=45)),
                ('homepage_url', models.CharField(max_length=70)),
            ],
            options={
                'db_table': 'company',
            },
        ),
    ]
