# Generated by Django 3.1.7 on 2021-04-19 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0003_auto_20210402_1326'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='nickname',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
